<?php

declare(strict_types=1);

namespace Blamodex\Lists\Tests\Unit;

use Blamodex\Lists\Models\ListItem;
use Blamodex\Lists\Models\Lists;
use Blamodex\Lists\Tests\Fixtures\DummyListable;
use Blamodex\Lists\Tests\Fixtures\DummyListOwner;
use Blamodex\Lists\Tests\TestCase;
use Illuminate\Database\QueryException;
use Illuminate\Support\Str;

class ListItemTest extends TestCase
{
    private DummyListOwner $owner;
    private Lists $list;

    protected function setUp(): void
    {
        parent::setUp();

        $this->owner = DummyListOwner::create([
            'name' => 'Test User',
            'email' => 'test@example.com',
        ]);

        $this->list = Lists::create([
            'name' => 'My Favorites',
            'lister_id' => $this->owner->id,
            'lister_type' => $this->owner->getMorphClass(),
        ]);
    }

    public function testCanCreateListItem(): void
    {
        $listable = DummyListable::create([
            'name' => 'Test Product',
            'description' => 'A test product',
        ]);

        $item = ListItem::create([
            'list_id' => $this->list->id,
            'listable_id' => $listable->id,
            'listable_type' => $listable->getMorphClass(),
        ]);

        $this->assertDatabaseHas('list_items', [
            'id' => $item->id,
            'list_id' => $this->list->id,
            'listable_id' => $listable->id,
            'listable_type' => DummyListable::class,
        ]);
    }

    public function testUuidIsAutoGenerated(): void
    {
        $listable = DummyListable::create([
            'name' => 'Test Product',
            'description' => 'A test product',
        ]);

        $item = ListItem::create([
            'list_id' => $this->list->id,
            'listable_id' => $listable->id,
            'listable_type' => $listable->getMorphClass(),
        ]);

        $this->assertNotEmpty($item->uuid);
        $this->assertTrue(Str::isUuid($item->uuid));
    }

    public function testUuidIsUniqueAcrossItems(): void
    {
        $listable1 = DummyListable::create(['name' => 'Product 1']);
        $listable2 = DummyListable::create(['name' => 'Product 2']);

        $item1 = ListItem::create([
            'list_id' => $this->list->id,
            'listable_id' => $listable1->id,
            'listable_type' => $listable1->getMorphClass(),
        ]);

        $item2 = ListItem::create([
            'list_id' => $this->list->id,
            'listable_id' => $listable2->id,
            'listable_type' => $listable2->getMorphClass(),
        ]);

        $this->assertNotEquals($item1->uuid, $item2->uuid);
    }

    public function testListRelationship(): void
    {
        $listable = DummyListable::create([
            'name' => 'Test Product',
            'description' => 'A test product',
        ]);

        $item = ListItem::create([
            'list_id' => $this->list->id,
            'listable_id' => $listable->id,
            'listable_type' => $listable->getMorphClass(),
        ]);

        $this->assertInstanceOf(Lists::class, $item->list);
        $this->assertEquals($this->list->id, $item->list->id);
    }

    public function testListRelationshipReturnsBelongsTo(): void
    {
        $item = new ListItem();

        $this->assertInstanceOf(
            \Illuminate\Database\Eloquent\Relations\BelongsTo::class,
            $item->list()
        );
    }

    public function testListableRelationship(): void
    {
        $listable = DummyListable::create([
            'name' => 'Test Product',
            'description' => 'A test product',
        ]);

        $item = ListItem::create([
            'list_id' => $this->list->id,
            'listable_id' => $listable->id,
            'listable_type' => $listable->getMorphClass(),
        ]);

        $this->assertInstanceOf(DummyListable::class, $item->listable);
        $this->assertEquals($listable->id, $item->listable->id);
    }

    public function testListableRelationshipReturnsMorphTo(): void
    {
        $item = new ListItem();

        $this->assertInstanceOf(
            \Illuminate\Database\Eloquent\Relations\MorphTo::class,
            $item->listable()
        );
    }

    public function testUniqueConstraintPreventsFullDuplicates(): void
    {
        $listable = DummyListable::create([
            'name' => 'Test Product',
            'description' => 'A test product',
        ]);

        ListItem::create([
            'list_id' => $this->list->id,
            'listable_id' => $listable->id,
            'listable_type' => $listable->getMorphClass(),
        ]);

        $this->expectException(QueryException::class);

        ListItem::create([
            'list_id' => $this->list->id,
            'listable_id' => $listable->id,
            'listable_type' => $listable->getMorphClass(),
        ]);
    }

    public function testSameItemCanBeInDifferentLists(): void
    {
        $listable = DummyListable::create([
            'name' => 'Test Product',
            'description' => 'A test product',
        ]);

        $list2 = Lists::create([
            'name' => 'Another List',
            'lister_id' => $this->owner->id,
            'lister_type' => $this->owner->getMorphClass(),
        ]);

        $item1 = ListItem::create([
            'list_id' => $this->list->id,
            'listable_id' => $listable->id,
            'listable_type' => $listable->getMorphClass(),
        ]);

        $item2 = ListItem::create([
            'list_id' => $list2->id,
            'listable_id' => $listable->id,
            'listable_type' => $listable->getMorphClass(),
        ]);

        $this->assertNotEquals($item1->id, $item2->id);
        $this->assertEquals($listable->id, $item1->listable_id);
        $this->assertEquals($listable->id, $item2->listable_id);
    }

    public function testDifferentItemsCanBeInSameList(): void
    {
        $listable1 = DummyListable::create(['name' => 'Product 1']);
        $listable2 = DummyListable::create(['name' => 'Product 2']);

        $item1 = ListItem::create([
            'list_id' => $this->list->id,
            'listable_id' => $listable1->id,
            'listable_type' => $listable1->getMorphClass(),
        ]);

        $item2 = ListItem::create([
            'list_id' => $this->list->id,
            'listable_id' => $listable2->id,
            'listable_type' => $listable2->getMorphClass(),
        ]);

        $this->assertNotEquals($item1->id, $item2->id);
        $this->assertEquals($this->list->id, $item1->list_id);
        $this->assertEquals($this->list->id, $item2->list_id);
    }

    public function testSoftDeletes(): void
    {
        $listable = DummyListable::create([
            'name' => 'Test Product',
            'description' => 'A test product',
        ]);

        $item = ListItem::create([
            'list_id' => $this->list->id,
            'listable_id' => $listable->id,
            'listable_type' => $listable->getMorphClass(),
        ]);

        $itemId = $item->id;
        $item->delete();

        $this->assertSoftDeleted('list_items', ['id' => $itemId]);
        $this->assertNull(ListItem::find($itemId));
        $this->assertNotNull(ListItem::withTrashed()->find($itemId));
    }

    public function testCanRestoreSoftDeletedItem(): void
    {
        $listable = DummyListable::create([
            'name' => 'Test Product',
            'description' => 'A test product',
        ]);

        $item = ListItem::create([
            'list_id' => $this->list->id,
            'listable_id' => $listable->id,
            'listable_type' => $listable->getMorphClass(),
        ]);

        $itemId = $item->id;
        $item->delete();

        $this->assertSoftDeleted('list_items', ['id' => $itemId]);

        $item->restore();

        $this->assertNotNull(ListItem::find($itemId));
        $this->assertNull(ListItem::find($itemId)->deleted_at);
    }

    public function testCanForceDeleteItem(): void
    {
        $listable = DummyListable::create([
            'name' => 'Test Product',
            'description' => 'A test product',
        ]);

        $item = ListItem::create([
            'list_id' => $this->list->id,
            'listable_id' => $listable->id,
            'listable_type' => $listable->getMorphClass(),
        ]);

        $itemId = $item->id;
        $item->forceDelete();

        $this->assertNull(ListItem::withTrashed()->find($itemId));
    }

    public function testUniqueIdsMethod(): void
    {
        $item = new ListItem();

        $this->assertEquals(['uuid'], $item->uniqueIds());
    }

    public function testGetTableMethod(): void
    {
        $item = new ListItem();

        $this->assertEquals('list_items', $item->getTable());
    }

    public function testGetTableUsesConfigValue(): void
    {
        config(['lists.table_names.list_items' => 'custom_list_items']);

        $item = new ListItem();

        $this->assertEquals('custom_list_items', $item->getTable());

        // Reset config
        config(['lists.table_names.list_items' => 'list_items']);
    }

    public function testListIdIsCastToInteger(): void
    {
        $listable = DummyListable::create([
            'name' => 'Test Product',
            'description' => 'A test product',
        ]);

        $item = ListItem::create([
            'list_id' => (string) $this->list->id,
            'listable_id' => $listable->id,
            'listable_type' => $listable->getMorphClass(),
        ]);

        $this->assertIsInt($item->list_id);
    }

    public function testListableIdIsCastToInteger(): void
    {
        $listable = DummyListable::create([
            'name' => 'Test Product',
            'description' => 'A test product',
        ]);

        $item = ListItem::create([
            'list_id' => $this->list->id,
            'listable_id' => (string) $listable->id,
            'listable_type' => $listable->getMorphClass(),
        ]);

        $this->assertIsInt($item->listable_id);
    }

    public function testFillableAttributes(): void
    {
        $item = new ListItem();
        $fillable = $item->getFillable();

        $this->assertContains('list_id', $fillable);
        $this->assertContains('listable_id', $fillable);
        $this->assertContains('listable_type', $fillable);
    }

    public function testTimestampsAreRecorded(): void
    {
        $listable = DummyListable::create([
            'name' => 'Test Product',
            'description' => 'A test product',
        ]);

        $item = ListItem::create([
            'list_id' => $this->list->id,
            'listable_id' => $listable->id,
            'listable_type' => $listable->getMorphClass(),
        ]);

        $this->assertNotNull($item->created_at);
        $this->assertNotNull($item->updated_at);
    }

    public function testItemBelongsToCorrectList(): void
    {
        $listable = DummyListable::create([
            'name' => 'Test Product',
            'description' => 'A test product',
        ]);

        $list2 = Lists::create([
            'name' => 'Another List',
            'lister_id' => $this->owner->id,
            'lister_type' => $this->owner->getMorphClass(),
        ]);

        $item1 = ListItem::create([
            'list_id' => $this->list->id,
            'listable_id' => $listable->id,
            'listable_type' => $listable->getMorphClass(),
        ]);

        $this->assertEquals($this->list->id, $item1->list->id);
        $this->assertNotEquals($list2->id, $item1->list->id);
    }
}
