<?php

declare(strict_types=1);

namespace Blamodex\Lists\Tests\Unit;

use Blamodex\Lists\Models\ListItem;
use Blamodex\Lists\Models\Lists;
use Blamodex\Lists\Tests\Fixtures\DummyListable;
use Blamodex\Lists\Tests\Fixtures\DummyListOwner;
use Blamodex\Lists\Tests\TestCase;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Support\Str;

class ListsTest extends TestCase
{
    private DummyListOwner $owner;

    protected function setUp(): void
    {
        parent::setUp();

        $this->owner = DummyListOwner::create([
            'name' => 'Test User',
            'email' => 'test@example.com',
        ]);
    }

    public function testCanCreateListWithOwner(): void
    {
        $list = Lists::create([
            'name' => 'My Favorites',
            'lister_id' => $this->owner->id,
            'lister_type' => $this->owner->getMorphClass(),
        ]);

        $this->assertDatabaseHas('lists', [
            'id' => $list->id,
            'name' => 'My Favorites',
            'lister_id' => $this->owner->id,
            'lister_type' => DummyListOwner::class,
        ]);
    }

    public function testSlugIsAutoGeneratedFromName(): void
    {
        $list = Lists::create([
            'name' => 'My Favorite Products',
            'lister_id' => $this->owner->id,
            'lister_type' => $this->owner->getMorphClass(),
        ]);

        $this->assertEquals('my-favorite-products', $list->slug);
    }

    public function testSlugIsNotOverwrittenIfProvided(): void
    {
        $list = Lists::create([
            'name' => 'My Favorite Products',
            'slug' => 'custom-slug',
            'lister_id' => $this->owner->id,
            'lister_type' => $this->owner->getMorphClass(),
        ]);

        $this->assertEquals('custom-slug', $list->slug);
    }

    public function testUuidIsAutoGenerated(): void
    {
        $list = Lists::create([
            'name' => 'My Favorites',
            'lister_id' => $this->owner->id,
            'lister_type' => $this->owner->getMorphClass(),
        ]);

        $this->assertNotEmpty($list->uuid);
        $this->assertTrue(Str::isUuid($list->uuid));
    }

    public function testUuidIsAlwaysGenerated(): void
    {
        // The HasUuids trait always generates a UUID for columns in uniqueIds()
        // This test verifies that behavior
        $list = Lists::create([
            'name' => 'My Favorites',
            'lister_id' => $this->owner->id,
            'lister_type' => $this->owner->getMorphClass(),
        ]);

        $this->assertNotEmpty($list->uuid);
        $this->assertTrue(Str::isUuid($list->uuid));

        // Even on a second list, a unique UUID is generated
        $list2 = Lists::create([
            'name' => 'Another List',
            'lister_id' => $this->owner->id,
            'lister_type' => $this->owner->getMorphClass(),
        ]);

        $this->assertNotEquals($list->uuid, $list2->uuid);
    }

    public function testListerRelationship(): void
    {
        $list = Lists::create([
            'name' => 'My Favorites',
            'lister_id' => $this->owner->id,
            'lister_type' => $this->owner->getMorphClass(),
        ]);

        $this->assertInstanceOf(DummyListOwner::class, $list->lister);
        $this->assertEquals($this->owner->id, $list->lister->id);
    }

    public function testItemsRelationship(): void
    {
        $list = Lists::create([
            'name' => 'My Favorites',
            'lister_id' => $this->owner->id,
            'lister_type' => $this->owner->getMorphClass(),
        ]);

        $listable = DummyListable::create([
            'name' => 'Test Product',
            'description' => 'A test product',
        ]);

        ListItem::create([
            'list_id' => $list->id,
            'listable_id' => $listable->id,
            'listable_type' => $listable->getMorphClass(),
        ]);

        $this->assertCount(1, $list->items);
        $this->assertInstanceOf(ListItem::class, $list->items->first());
    }

    public function testSoftDeletes(): void
    {
        $list = Lists::create([
            'name' => 'My Favorites',
            'lister_id' => $this->owner->id,
            'lister_type' => $this->owner->getMorphClass(),
        ]);

        $listId = $list->id;
        $list->delete();

        $this->assertSoftDeleted('lists', ['id' => $listId]);
        $this->assertNull(Lists::find($listId));
        $this->assertNotNull(Lists::withTrashed()->find($listId));
    }

    public function testAddItemMethod(): void
    {
        $list = Lists::create([
            'name' => 'My Favorites',
            'lister_id' => $this->owner->id,
            'lister_type' => $this->owner->getMorphClass(),
        ]);

        $listable = DummyListable::create([
            'name' => 'Test Product',
            'description' => 'A test product',
        ]);

        $item = $list->addItem($listable);

        $this->assertInstanceOf(ListItem::class, $item);
        $this->assertEquals($list->id, $item->list_id);
        $this->assertEquals($listable->id, $item->listable_id);
        $this->assertEquals($listable->getMorphClass(), $item->listable_type);
        $this->assertDatabaseHas('list_items', [
            'list_id' => $list->id,
            'listable_id' => $listable->id,
            'listable_type' => DummyListable::class,
        ]);
    }

    public function testAddItemDoesNotDuplicate(): void
    {
        $list = Lists::create([
            'name' => 'My Favorites',
            'lister_id' => $this->owner->id,
            'lister_type' => $this->owner->getMorphClass(),
        ]);

        $listable = DummyListable::create([
            'name' => 'Test Product',
            'description' => 'A test product',
        ]);

        $item1 = $list->addItem($listable);
        $item2 = $list->addItem($listable);

        $this->assertEquals($item1->id, $item2->id);
        $this->assertCount(1, $list->fresh()->items);
    }

    public function testAddItemsMethod(): void
    {
        $list = Lists::create([
            'name' => 'My Favorites',
            'lister_id' => $this->owner->id,
            'lister_type' => $this->owner->getMorphClass(),
        ]);

        $listable1 = DummyListable::create(['name' => 'Product 1']);
        $listable2 = DummyListable::create(['name' => 'Product 2']);
        $listable3 = DummyListable::create(['name' => 'Product 3']);

        $items = $list->addItems([$listable1, $listable2, $listable3]);

        $this->assertInstanceOf(Collection::class, $items);
        $this->assertCount(3, $items);
        $this->assertCount(3, $list->fresh()->items);
    }

    public function testRemoveItemMethod(): void
    {
        $list = Lists::create([
            'name' => 'My Favorites',
            'lister_id' => $this->owner->id,
            'lister_type' => $this->owner->getMorphClass(),
        ]);

        $listable = DummyListable::create([
            'name' => 'Test Product',
            'description' => 'A test product',
        ]);

        $list->addItem($listable);
        $this->assertCount(1, $list->fresh()->items);

        $result = $list->removeItem($listable);

        $this->assertTrue($result);
        $this->assertCount(0, $list->fresh()->items);
    }

    public function testRemoveItemReturnsFalseWhenNotFound(): void
    {
        $list = Lists::create([
            'name' => 'My Favorites',
            'lister_id' => $this->owner->id,
            'lister_type' => $this->owner->getMorphClass(),
        ]);

        $listable = DummyListable::create([
            'name' => 'Test Product',
            'description' => 'A test product',
        ]);

        $result = $list->removeItem($listable);

        $this->assertFalse($result);
    }

    public function testRemoveItemsMethod(): void
    {
        $list = Lists::create([
            'name' => 'My Favorites',
            'lister_id' => $this->owner->id,
            'lister_type' => $this->owner->getMorphClass(),
        ]);

        $listable1 = DummyListable::create(['name' => 'Product 1']);
        $listable2 = DummyListable::create(['name' => 'Product 2']);
        $listable3 = DummyListable::create(['name' => 'Product 3']);

        $list->addItems([$listable1, $listable2, $listable3]);
        $this->assertCount(3, $list->fresh()->items);

        $count = $list->removeItems([$listable1, $listable2]);

        $this->assertEquals(2, $count);
        $this->assertCount(1, $list->fresh()->items);
    }

    public function testRemoveItemsReturnsCountOfActuallyRemoved(): void
    {
        $list = Lists::create([
            'name' => 'My Favorites',
            'lister_id' => $this->owner->id,
            'lister_type' => $this->owner->getMorphClass(),
        ]);

        $listable1 = DummyListable::create(['name' => 'Product 1']);
        $listable2 = DummyListable::create(['name' => 'Product 2']);
        $listable3 = DummyListable::create(['name' => 'Product 3']);

        $list->addItem($listable1);

        // Try to remove 3 items, but only 1 exists in the list
        $count = $list->removeItems([$listable1, $listable2, $listable3]);

        $this->assertEquals(1, $count);
    }

    public function testHasItemMethod(): void
    {
        $list = Lists::create([
            'name' => 'My Favorites',
            'lister_id' => $this->owner->id,
            'lister_type' => $this->owner->getMorphClass(),
        ]);

        $listable = DummyListable::create([
            'name' => 'Test Product',
            'description' => 'A test product',
        ]);

        $this->assertFalse($list->hasItem($listable));

        $list->addItem($listable);

        $this->assertTrue($list->hasItem($listable));
    }

    public function testHasItemReturnsFalseAfterRemoval(): void
    {
        $list = Lists::create([
            'name' => 'My Favorites',
            'lister_id' => $this->owner->id,
            'lister_type' => $this->owner->getMorphClass(),
        ]);

        $listable = DummyListable::create([
            'name' => 'Test Product',
            'description' => 'A test product',
        ]);

        $list->addItem($listable);
        $this->assertTrue($list->hasItem($listable));

        $list->removeItem($listable);
        $this->assertFalse($list->hasItem($listable));
    }

    public function testUniqueIdsMethod(): void
    {
        $list = new Lists();

        $this->assertEquals(['uuid'], $list->uniqueIds());
    }

    public function testGetTableMethod(): void
    {
        $list = new Lists();

        $this->assertEquals('lists', $list->getTable());
    }

    public function testGetTableUsesConfigValue(): void
    {
        config(['lists.table_names.lists' => 'custom_lists']);

        $list = new Lists();

        $this->assertEquals('custom_lists', $list->getTable());

        // Reset config
        config(['lists.table_names.lists' => 'lists']);
    }

    public function testListerIdIsCastToInteger(): void
    {
        $list = Lists::create([
            'name' => 'My Favorites',
            'lister_id' => '123',
            'lister_type' => $this->owner->getMorphClass(),
        ]);

        $this->assertIsInt($list->lister_id);
    }

    public function testFillableAttributes(): void
    {
        $list = new Lists();
        $fillable = $list->getFillable();

        $this->assertContains('name', $fillable);
        $this->assertContains('slug', $fillable);
        $this->assertContains('lister_id', $fillable);
        $this->assertContains('lister_type', $fillable);
    }

    public function testTimestampsAreRecorded(): void
    {
        $list = Lists::create([
            'name' => 'My Favorites',
            'lister_id' => $this->owner->id,
            'lister_type' => $this->owner->getMorphClass(),
        ]);

        $this->assertNotNull($list->created_at);
        $this->assertNotNull($list->updated_at);
    }

    public function testCanUpdateList(): void
    {
        $list = Lists::create([
            'name' => 'My Favorites',
            'lister_id' => $this->owner->id,
            'lister_type' => $this->owner->getMorphClass(),
        ]);

        $list->update(['name' => 'Updated Name']);

        $this->assertEquals('Updated Name', $list->fresh()->name);
    }

    public function testSlugDoesNotChangeOnUpdate(): void
    {
        $list = Lists::create([
            'name' => 'My Favorites',
            'lister_id' => $this->owner->id,
            'lister_type' => $this->owner->getMorphClass(),
        ]);

        $originalSlug = $list->slug;

        $list->update(['name' => 'Updated Name']);

        $this->assertEquals($originalSlug, $list->fresh()->slug);
    }

    public function testCanForceDeleteList(): void
    {
        $list = Lists::create([
            'name' => 'My Favorites',
            'lister_id' => $this->owner->id,
            'lister_type' => $this->owner->getMorphClass(),
        ]);

        $listId = $list->id;
        $list->forceDelete();

        $this->assertNull(Lists::withTrashed()->find($listId));
    }

    public function testCanRestoreSoftDeletedList(): void
    {
        $list = Lists::create([
            'name' => 'My Favorites',
            'lister_id' => $this->owner->id,
            'lister_type' => $this->owner->getMorphClass(),
        ]);

        $listId = $list->id;
        $list->delete();

        $this->assertSoftDeleted('lists', ['id' => $listId]);

        $list->restore();

        $this->assertNotNull(Lists::find($listId));
        $this->assertNull(Lists::find($listId)->deleted_at);
    }

    public function testItemsRelationshipReturnsHasMany(): void
    {
        $list = new Lists();

        $this->assertInstanceOf(
            \Illuminate\Database\Eloquent\Relations\HasMany::class,
            $list->items()
        );
    }

    public function testListerRelationshipReturnsMorphTo(): void
    {
        $list = new Lists();

        $this->assertInstanceOf(
            \Illuminate\Database\Eloquent\Relations\MorphTo::class,
            $list->lister()
        );
    }
}
